const CANVAS_HEIGHT=512;
const CANVAS_WIDTH=288;
const bg=118;
let bgwidth=288;
const BACKGROUND=new Image();
const imgPath= "bg.png";
const PIPEUP=new Image();    
const PIPEDOWN=new Image();
const BASEGROUND=new Image();
const BIRD=new Image();
const START=new Image();
const RESTART=new Image();
const SCOREBOARD=new Image();
const BRONZE=new Image();
const SILVER=new Image();
const GOLD=new Image();
BACKGROUND.src=imgPath;
BASEGROUND.src="base.png";
var gameFrame;
PIPEUP.src="1.png";
PIPEDOWN.src="2.png";
BIRD.src="flappy3.png";
START.src="start.png";
BRONZE.src="bronzemedal.png";
SILVER.src="silvermedal.png";
GOLD.src="goldmedal.png";
RESTART.src="gameover.png";
SCOREBOARD.src="high-score.png"
let canvas=document.getElementById('canvas');
canvas.width=CANVAS_WIDTH;
canvas.height=CANVAS_HEIGHT;
let wing = new Audio('wing.wav');
let hit= new Audio('hit.wav');
let point=new Audio('point.wav');
var animation;
var pipeCreation;
var highScore;
let counter;

var junction_font = new FontFace('Flappy', 'url(Flappy-Bird.ttf)');
